apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: icgroup
  labels:
    env: prod
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Minimally Defined Server",
          "Group": "Server Group 1",
          "Host": "postgres",
          "Port": 5432,
          "Username": "ESGI",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        },
        "2": {
          "Name": "Backup Odoo DB",
          "Group": "Server Group 1",
          "Host": "postgres",
          "Port": 5432,
          "Username": "ESGI",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }

