apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: icgroup
  labels:
    env: prod
type: Opaque
data:
  POSTGRES_USER: RVNHSQ==
  POSTGRES_PASSWORD: RVNHSV81c3JjMg==
  PGADMIN_DEFAULT_EMAIL: dmxlbW9pbmU4QG15Z2VzLmZy
  PGADMIN_DEFAULT_PASSWORD: RVNHSV81c3JjMg==
