apiVersion: v1
kind: Service
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30083
      targetPort: 8080
  selector:
    app: ic-webapp

