apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30082
      targetPort: 80
  selector:
    app: pgadmin

