apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
        env: prod
    spec:
      containers:
        - name: odoo
          image: odoo:13.0
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: postgres
            - name: USER
              valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: POSTGRES_USER
            - name: PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: db-secret
                    key: POSTGRES_PASSWORD
          args: ["--", "--database=odoo", "-i", "base", "--db-filter=^odoo$"]
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-pvc

