apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  type: NodePort
  ports:
    - name: http
      port: 8069
      targetPort: 8069
      nodePort: 30080
      protocol: TCP
  selector:
    app: odoo

