apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: icgroup
  labels:
    app: postgres
    env: prod
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

